# infra/docker-compose.yml

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: schoolflow
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ..                   # go up one level: project root
      dockerfile: infra/Dockerfile.backend
    restart: on-failure
    working_dir: /app/backend
    volumes:
      - ../backend:/app/backend:rw  # mount your backend folder
      - ../ops:/app/backend/ops:rw  # mount your ops scripts
      - ./data/receipts:/tmp/receipts
    env_file:
      - ../.env
    depends_on:
      - db
    ports:
      - "8000:8000"                 # expose FastAPI on host port 8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
