"""Add fee models: plan, component, assignment, invoice, payment, receipt

Revision ID: b9bec1465e3a
Revises: 'a5daa4f83934'
Create Date: 2025-09-18 07:46:48.152043
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b9bec1465e3a'
down_revision: Union[str, Sequence[str], None] = 'a5daa4f83934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
