"""fix FK references to students.id

Revision ID: d29d4f37f099
Revises: 'b9bec1465e3a'
Create Date: 2025-09-22 15:32:17.415748
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd29d4f37f099'
down_revision: Union[str, Sequence[str], None] = 'b9bec1465e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'fee_assignment', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'fee_invoice', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fee_invoice', type_='foreignkey')
    op.drop_constraint(None, 'fee_assignment', type_='foreignkey')
    # ### end Alembic commands ###
