"""initial schema

Revision ID: f06fb140ee6c
Revises: None
Create Date: 2025-09-15 14:37:30.608207
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

print(">>> Running upgrade() from initial_schema")

# revision identifiers, used by Alembic.
revision: str = 'f06fb140ee6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_sections_academic_year'), 'class_sections', ['academic_year'], unique=False)
    op.create_index(op.f('ix_class_sections_id'), 'class_sections', ['id'], unique=False)
    op.create_index(op.f('ix_class_sections_name'), 'class_sections', ['name'], unique=False)
    op.create_table('fee_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_component_id'), 'fee_component', ['id'], unique=False)
    op.create_table('fee_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=64), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_invoice_id'), 'fee_invoice', ['id'], unique=False)
    op.create_table('fee_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_plan_id'), 'fee_plan', ['id'], unique=False)
    op.create_table('fee_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fee_plan_id', sa.Integer(), nullable=False),
    sa.Column('concession', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['fee_plan_id'], ['fee_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_assignment_id'), 'fee_assignment', ['id'], unique=False)
    op.create_table('fee_plan_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_plan_id', sa.Integer(), nullable=False),
    sa.Column('fee_component_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['fee_component_id'], ['fee_component.id'], ),
    sa.ForeignKeyConstraint(['fee_plan_id'], ['fee_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_plan_component_id'), 'fee_plan_component', ['id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_invoice_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_txn_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fee_invoice_id'], ['fee_invoice.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_txn_id', name='u_provider_txn')
    )
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    op.create_index(op.f('ix_payment_idempotency_key'), 'payment', ['idempotency_key'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('roll_number', sa.String(), nullable=False),
    sa.Column('class_section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_section_id'], ['class_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_roll_number'), 'students', ['roll_number'], unique=True)
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('receipt_no', sa.String(length=64), nullable=False),
    sa.Column('pdf_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_no')
    )
    op.create_index(op.f('ix_receipt_id'), 'receipt', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_id'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_index(op.f('ix_students_roll_number'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_payment_idempotency_key'), table_name='payment')
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_fee_plan_component_id'), table_name='fee_plan_component')
    op.drop_table('fee_plan_component')
    op.drop_index(op.f('ix_fee_assignment_id'), table_name='fee_assignment')
    op.drop_table('fee_assignment')
    op.drop_index(op.f('ix_fee_plan_id'), table_name='fee_plan')
    op.drop_table('fee_plan')
    op.drop_index(op.f('ix_fee_invoice_id'), table_name='fee_invoice')
    op.drop_table('fee_invoice')
    op.drop_index(op.f('ix_fee_component_id'), table_name='fee_component')
    op.drop_table('fee_component')
    op.drop_index(op.f('ix_class_sections_name'), table_name='class_sections')
    op.drop_index(op.f('ix_class_sections_id'), table_name='class_sections')
    op.drop_index(op.f('ix_class_sections_academic_year'), table_name='class_sections')
    op.drop_table('class_sections')
    # ### end Alembic commands ###
